export const FILM_DATA_ACTION_TYPES = Object.freeze({
    SET_FILM_DATA: 'SET_FILM_DATA',
    SET_FILM_LOADING: 'SET_FILM_LOADING',
    SET_FILM_ERROR: 'SET_FILM_ERROR',
    CLEAR_FILM_DATA: 'CLEAR_FILM_DATA',
})

export const SEARCH_DATA_ACTION_TYPES = Object.freeze({
    SET_SEARCH_RESULT_DATA: 'SET_SEARCH_RESULT_DATA',
    SET_SEARCH_LOADING: 'SET_SEARCH_LOADING',
    SET_SEARCH_ERROR: 'SET_SEARCH_ERROR',
    SET_SEARCH_IS_OPENED: 'SET_SEARCH_IS_OPENED',
    SET_SEARCH_INITIAL_VALUE: 'SET_SEARCH_INITIAL_VALUE',
})