export const GET_FILM_FULLDATA = 'GET_FILM_FULLDATA';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GET_FILMS_CARDS = 'GET_FILMS_CARDS';
export const GET_KEYWORDS_DATA = 'GET_KEYWORDS_DATA'
